### ISSUE TITLE
Error When Using ref.sql Macro

### ISSUE THREAD

**Issue by sdblanchard** [LewisDavies/upstream-prod#22]
Hello,

I recently installed upstream_prod in my dbt/snowflake instance. Our team uses custom schemas, and I was able to effectively load production data into my dev environment by replacing the refs in the model with upstream_prod.ref. However, I'm now encountering an error when attempting to overwrite the default macro with ref.sql. Specifically, I'm receiving a 'dbt_macro__ref' takes no more than 6 argument(s) error. Could you potentially provide some guidance on how to navigate this issue? Thank you.

![image](https://github.com/LewisDavies/upstream-prod/assets/48452045/8d1f02c0-92f4-423e-a8ca-2c2e502e2b84)

**Comment by LewisDavies** [comment]
Hey @sdblanchard, really sorry for the slow reply - having a new job and new kid doesn't allow much spare time! Which version of the package are you using? Since you're using dbt v1.3 you should be on v0.5.1 of the package (or earlier) and `macros/ref.sql` should look like [this](https://github.com/LewisDavies/upstream-prod/tree/0.5.1#3-update-ref).
