### ISSUE TITLE
Error with `prefer_recent` variable in ref.sql

### ISSUE THREAD

**Issue by andreviniciusmb** [LewisDavies/upstream-prod#31]
### Context

I want to configure the preference to select the latest model (even though it is in dev) or not, and this can be done using the variable `upstream_prod_prefer_recent`.

### Problem

Even setting the variable to False and not having the most up-to-date tables in my staging, the package continues to reference the tables in my staging.

Ex: As the `prefer_recent` variable is **False** and `dev_exists` is **True**, it could not be entered in the if command.

<img src="https://github.com/LewisDavies/upstream-prod/assets/44850779/2bdb05c6-fd2d-48ce-983c-587ead60a23c" width=700 height=300>

When I did this test checking if the variable was False, the if command did not enter.

<img src="https://github.com/LewisDavies/upstream-prod/assets/44850779/a6a6f060-b079-49be-89a2-7202c08cf74e" width=700 height=300>

**Comment by LewisDavies** [comment]
Thanks for catching this, and sorry for my slow reply. I've had this problem before when I haven't done a explicit comparison like `prefer_recent == false` - it's easy to miss because in Jinja it doesn't cause an error.

I've gone through the package and fixed any statements like this. I should be able to release a new version fixing this soon.

**Comment by LewisDavies** [comment]
@andreviniciusmb I've just merged a fix for this and will create a new release (v.0.8.1)
